# Instructor Do: Decision Trees

In [19]:
# Initial imports
import pandas as pd
from path import Path
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier





#import pandas as pd
#from path import Path
#from sklearn import tree
#from sklearn.preprocessing import StandardScaler
#from sklearn.model_selection import train_test_split
#from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

## Loading and Preprocessing Loans Encoded Data

In [2]:
# Loading data
file_path = Path("linear_regression_salary/Resources/loans_data_encoded_3.csv")
df_loans = pd.read_csv(file_path)
df_loans.head(20)

#file_path = Path("../Resources/loans_data_encoded.csv")
#df_loans = pd.read_csv(file_path)
#df_loans.head()

amount  term  age  bad  month_num  education_Bachelor  \
0     1000    30   45    0          6                   0   
1     1000    30   50    0          7                   1   
2     1000    30   33    0          8                   1   
3     1000    15   27    0          9                   0   
4     1000    30   28    0         10                   0   
5      300     7   35    0          7                   0   
6     1000    30   29    0          9                   0   
7     1000    30   36    0          5                   0   
8     1000    30   28    0          5                   0   
9      800    15   26    0          4                   0   
10     300     7   29    0          4                   0   
11    1000    15   39    0          9                   0   
12    1000    30   26    0         12                   0   
13     900     7   26    0          5                   0   
14    1000     7   27    0          5                   0   
15     800    15   26    0          7                   0   
16    1000    30   40    0          7                   0   
17    1000    15   32    0          1                   0   
18    1000    30   32    0          8                   0   
19     800    30   26    0          4                   0   

    education_High School or Below  education_Master or Above  \
0                                1                          0   
1                                0                          0   
2                                0                          0   
3                                0                          0   
4                                0                          0   
5                                0                          1   
6                                0                          0   
7                                0                          0   
8                                0                          0   
9                                0                          0   
10                               0                          0   
11                               1                          0   
12                               0                          0   
13                               0                          0   
14                               1                          0   
15                               0                          0   
16                               1                          0   
17                               1                          0   
18                               1                          0   
19                               0                          0   

    education_college  gender_female  gender_male  
0                   0              0            1  
1                   0              1            0  
2                   0              1            0  
3                   1              0            1  
4                   1              1            0  
5                   0              0            1  
6                   1              0            1  
7                   1              0            1  
8                   1              0            1  
9                   1              0            1  
10                  1              0            1  
11                  0              0            1  
12                  1              0            1  
13                  1              1            0  
14                  0              0            1  
15                  1              0            1  
16                  0              0            1  
17                  0              0            1  
18                  0              0            1  
19                  1              0            1

In [3]:
# Define features set
X = df_loans.copy()
X = X.drop("bad", axis=1)
X.head(20)

#X = df_loans.copy()
#X = X.drop("bad", axis=1)
#X.head()

amount  term  age  month_num  education_Bachelor  \
0     1000    30   45          6                   0   
1     1000    30   50          7                   1   
2     1000    30   33          8                   1   
3     1000    15   27          9                   0   
4     1000    30   28         10                   0   
5      300     7   35          7                   0   
6     1000    30   29          9                   0   
7     1000    30   36          5                   0   
8     1000    30   28          5                   0   
9      800    15   26          4                   0   
10     300     7   29          4                   0   
11    1000    15   39          9                   0   
12    1000    30   26         12                   0   
13     900     7   26          5                   0   
14    1000     7   27          5                   0   
15     800    15   26          7                   0   
16    1000    30   40          7                   0   
17    1000    15   32          1                   0   
18    1000    30   32          8                   0   
19     800    30   26          4                   0   

    education_High School or Below  education_Master or Above  \
0                                1                          0   
1                                0                          0   
2                                0                          0   
3                                0                          0   
4                                0                          0   
5                                0                          1   
6                                0                          0   
7                                0                          0   
8                                0                          0   
9                                0                          0   
10                               0                          0   
11                               1                          0   
12                               0                          0   
13                               0                          0   
14                               1                          0   
15                               0                          0   
16                               1                          0   
17                               1                          0   
18                               1                          0   
19                               0                          0   

    education_college  gender_female  gender_male  
0                   0              0            1  
1                   0              1            0  
2                   0              1            0  
3                   1              0            1  
4                   1              1            0  
5                   0              0            1  
6                   1              0            1  
7                   1              0            1  
8                   1              0            1  
9                   1              0            1  
10                  1              0            1  
11                  0              0            1  
12                  1              0            1  
13                  1              1            0  
14                  0              0            1  
15                  1              0            1  
16                  0              0            1  
17                  0              0            1  
18                  0              0            1  
19                  1              0            1

In [4]:
# Define target vector
y = df_loans["bad"].values
y[:20]


#y = df_loans["bad"].values.reshape(-1, 1)
#y[:5]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [5]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)



#X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [6]:
#Determine the shape of our trainig and testing sets.
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


#print(X_train.shape)
#print(X_test.shape)
#print(y_train.shape)
#print(y_test.shape)

(375, 10)
(125, 10)
(375,)
(125,)


In [7]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, random_state=78, train_size=0.80)

In [8]:
print(X_train2.shape)
print(X_test2.shape)
print(y_train2.shape)
print(y_test2.shape)

(400, 10)
(100, 10)
(400,)
(100,)


In [9]:
# Creating StandardScaler instance
scaler = StandardScaler()

#scaler = StandardScaler()

In [10]:
# Fitting Standard Scaller
X_scaler = scaler.fit(X_train)

#X_scaler = scaler.fit(X_train)

In [11]:
# Scaling data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


#X_train_scaled = X_scaler.transform(X_train)
#X_test_scaled = X_scaler.transform(X_test)


## Fitting the Decision Tree Model

In [12]:
# Creating the decision tree classifier instance
model = tree.DecisionTreeClassifier()



# model = tree.DecisionTreeClassifier()

In [13]:
# Fitting the model
model = model.fit(X_train_scaled, y_train)


#model = model.fit(X_train_scaled, y_train)

## Making Predictions Using the Tree Model

In [14]:
# Making predictions using the testing data
predictions = model.predict(X_test_scaled)


#predictions = model.predict(X_test_scaled)

In [15]:
predictions

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0], dtype=int64)

## Model Evaluation

In [17]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)

#Create a DataFram from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])


cm_df

#cm = confusion_matrix(y_test, predictions)
#cm_df = pd.DataFrame(
#    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
#)

# Calculating the accuracy score
#acc_score = accuracy_score(y_test, predictions)

Predicted 0  Predicted 1
Actual 0           53           31
Actual 1           22           19

In [18]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))


Confusion Matrix


Predicted 0  Predicted 1
Actual 0           53           31
Actual 1           22           19

Accuracy Score : 0.576
Classification Report
              precision    recall  f1-score   support

           0       0.71      0.63      0.67        84
           1       0.38      0.46      0.42        41

    accuracy                           0.58       125
   macro avg       0.54      0.55      0.54       125
weighted avg       0.60      0.58      0.58       125



In [20]:
#Loading new data for random forests exercise
file_path2 = Path("linear_regression_salary/Resources/loans_data_encoded_3.csv")
df_loans2 = pd.read_csv(file_path2)
df_loans2.head(20)

amount  term  age  bad  month_num  education_Bachelor  \
0     1000    30   45    0          6                   0   
1     1000    30   50    0          7                   1   
2     1000    30   33    0          8                   1   
3     1000    15   27    0          9                   0   
4     1000    30   28    0         10                   0   
5      300     7   35    0          7                   0   
6     1000    30   29    0          9                   0   
7     1000    30   36    0          5                   0   
8     1000    30   28    0          5                   0   
9      800    15   26    0          4                   0   
10     300     7   29    0          4                   0   
11    1000    15   39    0          9                   0   
12    1000    30   26    0         12                   0   
13     900     7   26    0          5                   0   
14    1000     7   27    0          5                   0   
15     800    15   26    0          7                   0   
16    1000    30   40    0          7                   0   
17    1000    15   32    0          1                   0   
18    1000    30   32    0          8                   0   
19     800    30   26    0          4                   0   

    education_High School or Below  education_Master or Above  \
0                                1                          0   
1                                0                          0   
2                                0                          0   
3                                0                          0   
4                                0                          0   
5                                0                          1   
6                                0                          0   
7                                0                          0   
8                                0                          0   
9                                0                          0   
10                               0                          0   
11                               1                          0   
12                               0                          0   
13                               0                          0   
14                               1                          0   
15                               0                          0   
16                               1                          0   
17                               1                          0   
18                               1                          0   
19                               0                          0   

    education_college  gender_female  gender_male  
0                   0              0            1  
1                   0              1            0  
2                   0              1            0  
3                   1              0            1  
4                   1              1            0  
5                   0              0            1  
6                   1              0            1  
7                   1              0            1  
8                   1              0            1  
9                   1              0            1  
10                  1              0            1  
11                  0              0            1  
12                  1              0            1  
13                  1              1            0  
14                  0              0            1  
15                  1              0            1  
16                  0              0            1  
17                  0              0            1  
18                  0              0            1  
19                  1              0            1

In [21]:
#Define the features set.
X = df_loans2.copy()
X = X.drop("bad", axis=1)
X.head(20)

amount  term  age  month_num  education_Bachelor  \
0     1000    30   45          6                   0   
1     1000    30   50          7                   1   
2     1000    30   33          8                   1   
3     1000    15   27          9                   0   
4     1000    30   28         10                   0   
5      300     7   35          7                   0   
6     1000    30   29          9                   0   
7     1000    30   36          5                   0   
8     1000    30   28          5                   0   
9      800    15   26          4                   0   
10     300     7   29          4                   0   
11    1000    15   39          9                   0   
12    1000    30   26         12                   0   
13     900     7   26          5                   0   
14    1000     7   27          5                   0   
15     800    15   26          7                   0   
16    1000    30   40          7                   0   
17    1000    15   32          1                   0   
18    1000    30   32          8                   0   
19     800    30   26          4                   0   

    education_High School or Below  education_Master or Above  \
0                                1                          0   
1                                0                          0   
2                                0                          0   
3                                0                          0   
4                                0                          0   
5                                0                          1   
6                                0                          0   
7                                0                          0   
8                                0                          0   
9                                0                          0   
10                               0                          0   
11                               1                          0   
12                               0                          0   
13                               0                          0   
14                               1                          0   
15                               0                          0   
16                               1                          0   
17                               1                          0   
18                               1                          0   
19                               0                          0   

    education_college  gender_female  gender_male  
0                   0              0            1  
1                   0              1            0  
2                   0              1            0  
3                   1              0            1  
4                   1              1            0  
5                   0              0            1  
6                   1              0            1  
7                   1              0            1  
8                   1              0            1  
9                   1              0            1  
10                  1              0            1  
11                  0              0            1  
12                  1              0            1  
13                  1              1            0  
14                  0              0            1  
15                  1              0            1  
16                  0              0            1  
17                  0              0            1  
18                  0              0            1  
19                  1              0            1

In [22]:
#Define the target set.
y = df_loans2["bad"].ravel()
y[:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [23]:
#Splitting into Train and Test sets.
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, random_state=78)

In [24]:
#Creating a StandardScaler instance.
scaler2 = StandardScaler()
#Fitting the Standard Scaler with the training data.
X_scaler2 = scaler2.fit(X_train2)

In [25]:
#Scaling the data.
X_train_scaled2 = X_scaler2.transform(X_train2)
X_test_scaled2 = X_scaler2.transform(X_test2)

In [26]:
#Creating random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

In [27]:
rf_model

RandomForestClassifier(n_estimators=128, random_state=78)

In [28]:
#Fitting the model.
rf_model = rf_model.fit(X_train_scaled2, y_train2)

In [29]:
#Making predictions using the testing data.
predictions2 = rf_model.predict(X_test_scaled2)
predictions2

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1], dtype=int64)

In [30]:
# Calculating the confusion matrix.
cm2 = confusion_matrix(y_test2, predictions2)

# Create a DataFrame from the confusion matrix.
cm2_df = pd.DataFrame(
    cm2, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm2_df

Predicted 0  Predicted 1
Actual 0           51           33
Actual 1           23           18

In [32]:
# Calculating the accuracy score.
acc_score2 = accuracy_score(y_test2, predictions2)
acc_score2

0.552

In [33]:
# Displaying results
print("Confusion Matrix")
display(cm2_df)
print(f"Accuracy Score : {acc_score2}")
print("Classification Report")
print(classification_report(y_test2, predictions2))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0           51           33
Actual 1           23           18

Accuracy Score : 0.552
Classification Report
              precision    recall  f1-score   support

           0       0.69      0.61      0.65        84
           1       0.35      0.44      0.39        41

    accuracy                           0.55       125
   macro avg       0.52      0.52      0.52       125
weighted avg       0.58      0.55      0.56       125



In [34]:
#Calculating feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.05454782, 0.07997292, 0.43280448, 0.32973986, 0.01887172,
       0.02110219, 0.00271658, 0.02151063, 0.01887818, 0.01985562])

In [35]:
#Sort features by importance
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.43280447750315343, 'age'),
 (0.32973986443922343, 'month_num'),
 (0.07997292251445517, 'term'),
 (0.05454782107242418, 'amount'),
 (0.021510631303272416, 'education_college'),
 (0.021102188881175144, 'education_High School or Below'),
 (0.01985561654170213, 'gender_male'),
 (0.018878176828577283, 'gender_female'),
 (0.018871722006693077, 'education_Bachelor'),
 (0.002716578909323729, 'education_Master or Above')]

In [36]:
#To improve this model, we can drop some of the lower ranked features.

In [37]:
#In summary, bootstrapping is simply a sampling technique with which a number of samples are made, 
#and in which an observation can occur multiple times.

In [38]:
#In the aggregation step, different classifiers are run, using the samples drawn in the 
#bootstrapping stage. Each classifier is run independently of the others, and 
#all the results are aggregated via a voting process. Each classifier will vote 
#for a label (a prediction). The final prediction is the one with the most votes.

In [39]:
#Boosting is another technique to combine weak learners into a strong learner.
#In boosting, however, the weak learners are not combined at the same time. 
#Instead, they are used sequentially, as one model learns from the mistakes of the previous model.